
version: 0.2

env:
  variables:
    PACKAGE_OUTPUT_BUCKET: nod15c.lambda
    SAM_DEPLOY_TEMPLATE: deploy.yml
    # Expanded later
    MAKETOOLS: "${CODEBUILD_SRC_DIR_tools}"
  parameter-store:
    NOD15C_NPM_TOKEN: "${NPM_TOKEN_PARAM_KEY}"

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # These come from passing GitHubSourceVariables (CODEBUILD_SOURCE_REPO_URL, etc. are empty when triggered from CPL)
      - "echo COMMIT_ID: $COMMIT_ID"
      - "echo COMMIT_BRANCH: $COMMIT_BRANCH"
  build:
    commands:
      # Lambdas
      - make build
      - make lint
      - make test
      # SAM
      - |
        sam package \
          --template-file ./template.yml \
          --output-template-file $SAM_DEPLOY_TEMPLATE \
          --s3-bucket nod15c.lambda

artifacts:
  files:
    - $SAM_DEPLOY_TEMPLATE


