
  parser: '@typescript-eslint/parser'
  root: true
  parserOptions:
    ecmaVersion: 2018,
    sourceType: module
  plugins:
    - '@typescript-eslint'
  env:
    es6: true,
    node: true,
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier/@typescript-eslint
    - plugin:prettier/recommended
  rules:
    quotes:
      - error
      - single
      - allowTemplateLiterals: true
        avoidEscape: true
    semi:
      - error
      - never
    '@typescript-eslint/member-delimiter-style':
      - error
      - multiline:
          delimiter: comma
          requireLast: false
      - singleline:
          delimiter: 'comma',
          requireLast: false,
    '@typescript-eslint/no-this-alias':
      - error
      - allowDestructuring: true
        allowedNames:
          - self





